# -------------------------------------------------------
# Ansible Inventory
# Replace 34.230.90.16 with the IP from: terraform output
# -------------------------------------------------------

[devops_server]
34.230.90.16 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/terraformboot.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
